services:
  mariadb:
    image: mariadb
    environment: 
      - MARIADB_USER=${LOGIN_BD}
      - MARIADB_PASSWORD=${MDP_BD}
      - MARIADB_DATABASE=${NOM_BD}
      - MARIADB_ROOT_PASSWORD=${MDP_ROOT}
    ports:
      - 3306:3306
    volumes:
      - C:\Users\Corentin\Documents\USMB\s4\info411\info411\db_data:/var/lib/mysql
  monapache:
    image: corentinbess/monapache
    environment: 
      - USER_BD=${LOGIN_BD}
      - PASS_BD=${MDP_BD}
      - SERVEUR_WEB=${HOST}
      - NOM_BD=${NOM_BD}
    volumes:
      - .:/var/www/html
    ports:
      - "${PORT_SITE}:80"
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "${PORT_PHPMYADMIN}:80"
  monubuntu:
    image: corentinbess/monubuntu